---

- name: Clone Rails App Repo
  git: repo={{ gitRepo }}
       dest={{ gitDest }}
       version={{ gitVersion }}
       accept_hostkey=yes

- name: Copy DB Template
  template: src=database.postgresql.yml.j2
            dest=/home/{{ username }}/app/config/database.yml

- name: install prerequisits
  apt: name={{ item }}
       state=latest
       update_cache=yes
  with_items:
    - libcurl3-dev
  sudo: yes

- name: install Bundle
  raw: export PATH=${HOME}/.rvm/bin:${PATH} && bash -lc 'gem install bundle'

- name: Exec Bundler
  raw: export PATH=${HOME}/.rvm/bin:${PATH} && cd /home/{{ username }}/app && bash -lc 'bundle install'

- name: Rake DB Setup
  raw: export PATH=${HOME}/.rvm/bin:${PATH} && cd /home/{{ username }}/app && bash -lc 'rake db:create'
  when: INITDB is defined

- name: Rake DB schema
  raw: export PATH=${HOME}/.rvm/bin:${PATH} && cd /home/{{ username }}/app && bash -lc 'rake db:schema:load'
  when: INITDB is defined

- name: Rake DB Seed
  raw: export PATH=${HOME}/.rvm/bin:${PATH} && cd /home/{{ username }}/app && bash -lc 'rake db:seed'
  when: SEEDDB is defined

- name: Rake DB Migrate
  raw: export PATH=${HOME}/.rvm/bin:${PATH} && cd /home/{{ username }}/app && bash -lc 'rake db:migrate'
  when: MIGRATE is defined

- name: Rake Assets Precompile
  raw: export PATH=${HOME}/.rvm/bin:${PATH} && cd /home/{{ username }}/app && bash -lc 'rake assets:precompile'

- name: restart apache2
  service: name=apache2
           state=restarted
  sudo: yes
